image: node:14

before_script:
  - npm install
  - npm run lint

cache:
  paths:
    - node_modules/

test:
  script:
    - npm run coverage
  artifacts:
    paths:
      - coverage

pages:
  script:
    - npm run doc
    - mv ./docs ./public
  artifacts:
    paths:
      - public